### ISSUE TITLE
error

### ISSUE THREAD

**Issue by lshxx** [Whiteshark-314/TOuNN#1]
I want to ask if the getcondvects_n_k function is written by myself. I got this error when I ran it. "error location_sampling (line 36)
    xyz=dlarray(single(flip(getcondvects_n_k([prob.nely; prob.nelx; prob.nelz], 3, val_vectors),2)),'BC');"

**Comment by Whiteshark-314** [comment]
My bad. That function was on the path in MATLAB on my PC as I use that function for various other projects. I have added it to this repo now.
